# Generated by Django 5.1.4 on 2024-12-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='required_documents',
        ),
    ]
